// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDdV6PgYsf_B_aPF1qXVl_t8iEiP-Z1zs',
    appId: '1:740069106034:web:36a0d9345829b48ab0fdeb',
    messagingSenderId: '740069106034',
    projectId: 'fa19-bcs-002',
    authDomain: 'fa19-bcs-002.firebaseapp.com',
    storageBucket: 'fa19-bcs-002.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrEOHRimWi6FIksT2XxEVBRLJlCsNzX0g',
    appId: '1:740069106034:android:db2fecfc84c88b02b0fdeb',
    messagingSenderId: '740069106034',
    projectId: 'fa19-bcs-002',
    storageBucket: 'fa19-bcs-002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7qOE0Epb0sljJ-Hfuf4-i-eaCZ_CYbpQ',
    appId: '1:740069106034:ios:88943211042a0d71b0fdeb',
    messagingSenderId: '740069106034',
    projectId: 'fa19-bcs-002',
    storageBucket: 'fa19-bcs-002.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7qOE0Epb0sljJ-Hfuf4-i-eaCZ_CYbpQ',
    appId: '1:740069106034:ios:88943211042a0d71b0fdeb',
    messagingSenderId: '740069106034',
    projectId: 'fa19-bcs-002',
    storageBucket: 'fa19-bcs-002.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDdV6PgYsf_B_aPF1qXVl_t8iEiP-Z1zs',
    appId: '1:740069106034:web:90c4c100c9e8133ab0fdeb',
    messagingSenderId: '740069106034',
    projectId: 'fa19-bcs-002',
    authDomain: 'fa19-bcs-002.firebaseapp.com',
    storageBucket: 'fa19-bcs-002.firebasestorage.app',
  );
}
